remote_theme: vaibhavvikas/jekyll-theme-minimalistic
title: Book Of AppStudio
description: Technical documents about the Managed Developer Platform
color-scheme: auto
navigation:
  - name: Technical Overview Document
    link: /book/index.html
  - name: API References
    link: /book/ref/index.html
    sublist: 
    - name: Application Service (HAS)
      link: /book/ref/application-service.html
    - name: Service Provider (SPI)
      link: /book/ref/service-provider.html
    - name: GitOps Service
      link: /book/ref/gitops-service.html
    - name: Environment API
      link: /book/ref/environment.html
    - name: Control Plane (KCP)
      limk: /book/ref/kcp.html