remote_theme: vaibhavvikas/jekyll-theme-minimalistic
title: Book Of AppStudio
description: Technical documents about the Managed Developer Platform
color-scheme: auto
navigation:
  - name: Technical Overview Document
    link: /book/book/index.html
  - name: Architecture Decision Records
    link: /book/ADR/index.html
  - name: API References
    link: /book/ref/index.html
    sublist: 
    - name: Application and Environment API
      link: /book/ref/application-environment-api.html
    - name: Service Provider (SPI)
      link: /book/ref/service-provider.html
    - name: GitOps Service
      link: /book/ref/gitops.html
    - name: Control Plane (KCP)
      link: /book/ref/kcp.html